---

- name: install python software properties
  apt: pkg=python-software-properties state=latest force=yes update_cache=yes

- name: install ca ceritificates
  apt: pkg=ca-certificates state=latest

- name: install the postgresql.org signing key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present id=ACCC4CF8

- name: install postgresql apt source
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main' state=present

- name: install postgres
  apt: pkg=postgresql-9.3 state=latest force=yes

- name: install postgres contrib
  apt: pkg=postgresql-contrib-9.3 state=latest force=yes

- name: Configure shred memory
  shell: echo 4294967295 > /proc/sys/kernel/shmmax && echo "kernel.shmmax=4294967295" >> /etc/sysctl.conf

- name: install Python PostgreSQL database adapter.
  apt: pkg=python-psycopg2 state=latest force=yes

- name: create postgres configs folder
  file: path=/etc/postgresql/9.3/main state=directory owner=postgres

- name: configure postgres
  template: src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf mode=644

- name: configure pg_hba
  template: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf mode=644

- name: Restart PostgreSQL
  shell: /etc/init.d/postgresql restart

- name: create dhis database
  postgresql_db: name=dhis2

- name: create dhis user
  postgresql_user: name=dhis password=password db=dhis2

- name: create hibernate home
  file: path={{ dhis_home }} mode=0777 state=directory

- name: copy hibernate properties to DHIS home
  template: src=hibernate.properties dest={{ dhis_home }} mode=0755
